name: lf
channels:
  - conda-forge
dependencies:
  - llvmdev=11.1.0
  - toml
  - pytest
  - jupyter
  - xeus
  - xeus-zmq
  - xtl
  - nlohmann_json
  - cppzmq
  - jupyter_kernel_test
  - xonsh
  - re2c
  - numpy
  - bison=3.4
  - rapidjson
  - ninja
